import imaplib
from email.mime.text import MIMEText
from email.header import Header
from email.utils import formatdate


def get_imap_connection(host,username,password,initialmailbox="INBOX",ssl=False,assertEmpty=True):
    imap=None
    if ssl:
        imap=imaplib.IMAP4_SSL(host=host,port=imaplib.IMAP4_SSL_PORT)
    else:
        imap=imaplib.IMAP4(host=host,port=imaplib.IMAP4_PORT)
    imap.login(username,password)
    
    #make sure the configured folder exists
    t,c=imap.select(initialmailbox)
    if t=='NO':
        raise Exception("Folder %s does not exist: %s"%initialmailbox)
    if assertEmpty:
        messagecount=int(c[0])
        assert messagecount==0,"mailbox is not empty, contains %s messages"%messagecount
    return imap
    
def create_dummy_txt_messages(amount,sender="sender@example.com",recipient="recipient@example.org" ):
    
    for no in range(amount):
        no=str(no).zfill(5)
        body="hello world # %s"%no
        txt = MIMEText(body, u'plain')
            
        txt[u'Subject'] = Header('[Autogenerated] #%s'%no).encode()
        txt[u'To'] = Header(recipient)
        txt[u'From'] = Header(sender)
        txt[u'Date'] = Header(formatdate(localtime=True))
        txt[u'x-generated-num'] = Header(str(no))
        yield txt
